#+TITLE:       Why this Year I'm Focusing on Charity.
#+DATE:        2014-12-03
#+TAGS:        personal
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

I am fortunate in my life that I have nurtured a career that not only helps to sustain my family but allows me enough money to enjoy some recreational things. It is for this reason that I'm not sure whether my growing distaste for consumerism has just come with age, or if it's because I can afford things I would like. Either way, I have come to loathe this time of year in The United States.

I feel inundated by commercials telling me to buy now, that I should get what I really want this year. Here's a BMW that I deserve. Here's a diamond necklace he had better get me. Here's me suppressing a gag reflex.

I'm not out and out against people wanting things -- or gifts. That's all fine (I even have a few items on my list). It's the exuberance of what the last fourth of the year has come to represent. We have an entire season of procurement and societal greed. I've reached a tipping point in my life where the very idea of me sitting down and putting thought into a list of more things I want to acquire leaves a bad taste in my mouth. I don't need more stuff -- no matter how hard the advertising industry tries to sell it. What I would like to do this year is cultivate compassion, and establish a pattern my newborn daughter can look up to. When I think of this time of year, I don't want to think of the exuberance of excess, I want to think of others, and how I can possibly contribute in some small way to the betterment of the world.

So last night I sat down and I did make a list. I made a list of charities I'd like to support this year, and going forward. If you're in a position where you don't really need anything, I encourage you to at least stop and think about what this time of year means to you, and whether more things will really enhance your life.

Happy holidays, everyone.

Katherine

- NAMI ([[http://www.charitynavigator.org/index.cfm?bay%3Dsearch.summary&orgid%3D4827][National Alliance on Mental Illness]])
- HRC ([[http://www.charitynavigator.org/index.cfm?bay%3Dsearch.summary&orgid%3D6229][The Human Rights Campaign]])
- WWF ([[http://www.charitynavigator.org/index.cfm?bay%3Dsearch.summary&orgid%3D4770][World Wildlife Fund]])
- Wikimedia Foundation ([[http://www.charitynavigator.org/index.cfm?bay%3Dsearch.summary&orgid%3D11212][Wikipedia]])
